//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class BankovniNalozi
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BankovniNalozi()
        {
            this.Adrese = new HashSet<Adrese>();
        }
    
        public int Id { get; set; }
        public string BrojZiroRacuna { get; set; }
        public string NazivVlasnika { get; set; }
        public string NazivBanke { get; set; }
        public string Drzava { get; set; }
        public string Firma { get; set; }
        public string Radnik { get; set; }
        public Nullable<int> Kupac { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Adrese> Adrese { get; set; }
        public virtual Firme Firme { get; set; }
        public virtual Kupci Kupci { get; set; }
        public virtual Radnici Radnici { get; set; }
    }
}
