//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dijelovi
    {
        public int Id { get; set; }
        public string EnNaziv { get; set; }
        public string SrNaziv { get; set; }
        public Nullable<short> StepenOstecenja { get; set; }
        public string Slika { get; set; }
        public int Automobil { get; set; }
        public Nullable<int> Prodavac { get; set; }
    
        public virtual Automobili Automobili { get; set; }
        public virtual Prodavci Prodavci { get; set; }
    }
}
