//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class KorisnickiNalozi
    {
        public string KorisnickoIme { get; set; }
        public string Lozinka { get; set; }
        public string Radnik { get; set; }
        public Nullable<int> Kupac { get; set; }
        public short Tip { get; set; }
        public string Opis { get; set; }
    
        public virtual Kupci Kupci { get; set; }
        public virtual Radnici Radnici { get; set; }
    }
}
