//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class stovariste_dev_dbEntities : DbContext
    {
        public stovariste_dev_dbEntities()
            : base("name=stovariste_dev_dbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Adrese> Adrese { get; set; }
        public virtual DbSet<Automobili> Automobilis { get; set; }
        public virtual DbSet<BankovniNalozi> BankovniNalozis { get; set; }
        public virtual DbSet<Dijelovi> Dijelovi { get; set; }
        public virtual DbSet<BrojeviVrata> BrojeviVratas { get; set; }
        public virtual DbSet<Cijene> Cijenes { get; set; }
        public virtual DbSet<Firme> Firmes { get; set; }
        public virtual DbSet<GodineProizvodnje> GodineProizvodnjes { get; set; }
        public virtual DbSet<KorisnickiNalozi> KorisnickiNalozis { get; set; }
        public virtual DbSet<Kupci> Kupcis { get; set; }
        public virtual DbSet<MarkeAutomobila> MarkeAutomobilas { get; set; }
        public virtual DbSet<ModeliAutomobila> ModeliAutomobilas { get; set; }
        public virtual DbSet<Prodavci> Prodavcis { get; set; }
        public virtual DbSet<Rabati> Rabatis { get; set; }
        public virtual DbSet<Radnici> Radnicis { get; set; }
        public virtual DbSet<TipoviMjenjaca> TipoviMjenjacas { get; set; }
        public virtual DbSet<VrsteGoriva> VrsteGorivas { get; set; }
    }
}
