CREATE TABLE [dbo].[Adrese]
(
	[Id] INT NOT NULL PRIMARY KEY IDENTITY(1,1), 
    [Ulica] VARCHAR(50) NOT NULL, 
    [Broj] INT NOT NULL, 
    [Grad] VARCHAR(50) NOT NULL, 
    [Drzava] VARCHAR(50) NOT NULL, 
    [Radnik] CHAR(13) NULL,
	[Firma] VARCHAR(50) NULL, 
    [BankovniNalog] INT NULL, 
    [Prodavac] INT NULL, 
    CONSTRAINT ADRESA_RADNIK_FK FOREIGN KEY (Radnik) REFERENCES Radnici(JMBG),
	CONSTRAINT ADRESA_FIRMA_FK FOREIGN KEY (Firma) REFERENCES Firme(PIB),
	CONSTRAINT ADRESA_BANKOVNI_NALOG_FK FOREIGN KEY (BankovniNalog) REFERENCES BankovniNalozi(id),
	CONSTRAINT ADRESA_PRODAVAC_FK FOREIGN KEY (Prodavac) REFERENCES Prodavci(id)
)
