CREATE TABLE [dbo].[BankovniNalozi]
(
	[Id] INT NOT NULL PRIMARY KEY IDENTITY(1,1), 
    [BrojZiroRacuna] VARCHAR(50) NOT NULL, 
    [NazivVlasnika] VARCHAR(50) NOT NULL, 
    [NazivBanke] VARCHAR(50) NOT NULL, 
    [Drzava] NCHAR(10) NOT NULL, 
    [Firma] VARCHAR(50) NULL,
	[Radnik] CHAR(13) NULL, 
    [Kupac] INT NULL, 
    CONSTRAINT BANKOVI_NALOG_FIRMA_FK FOREIGN KEY (Firma) REFERENCES Firme(PIB),
	CONSTRAINT BANKOVI_NALOG_RADNIK_FK FOREIGN KEY (Radnik) REFERENCES Radnici(JMBG),
	CONSTRAINT BANKOVI_NALOG_KUPAC_FK FOREIGN KEY (Kupac) REFERENCES Kupci(id),
)
