CREATE TABLE [dbo].[KorisnickiNalozi]
(
	[KorisnickoIme] VARCHAR(20) NOT NULL PRIMARY KEY, 
    [Lozinka] VARCHAR(20) NOT NULL, 
    [Radnik] CHAR(13) NULL, 
    [Kupac] INT NULL,
	[Tip] SMALLINT NOT NULL, 
    [Opis] VARCHAR(500) NULL, 
    CONSTRAINT KORISNICKI_NALOG_RADNIK_FK FOREIGN KEY (Radnik) REFERENCES Radnici(JMBG),
	CONSTRAINT KORISNICKI_NALOG_KUPAC_FK FOREIGN KEY (Kupac) REFERENCES Kupci(id),
)
