CREATE TABLE [dbo].[Kupci]
(
	[Id] INT NOT NULL PRIMARY KEY IDENTITY(1,1), 
    [Ime] VARCHAR(50) NOT NULL, 
    [Prezime] VARCHAR(50) NOT NULL, 
    [BrojTelefona] VARCHAR(50) NOT NULL, 
    [Firma] VARCHAR(50) NULL,
	[Mejl] VARCHAR(50) NULL, 
    [Rabat] INT NULL, 
    CONSTRAINT KUPAC_FIRMA_FK FOREIGN KEY (Firma) REFERENCES Firme(PIB),
	CONSTRAINT KUPAC_RABAT_FK FOREIGN KEY (Rabat) REFERENCES Rabati(id)
)
