//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Podaci
{
    using System;
    using System.Collections.Generic;
    
    public partial class Adrese
    {
        public int Id { get; set; }
        public string Ulica { get; set; }
        public int Broj { get; set; }
        public string Grad { get; set; }
        public string Drzava { get; set; }
        public string Radnik { get; set; }
        public string Firma { get; set; }
        public Nullable<int> BankovniNalog { get; set; }
        public Nullable<int> Prodavac { get; set; }
    
        public virtual BankovniNalozi BankovniNalozi { get; set; }
        public virtual Firme Firme { get; set; }
        public virtual Prodavci Prodavci { get; set; }
        public virtual Radnici Radnici { get; set; }
    }
}
