//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Podaci
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class stovariste_dev_dbEntities1 : DbContext
    {
        public stovariste_dev_dbEntities1()
            : base("name=stovariste_dev_dbEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Adrese> Adrese { get; set; }
        public virtual DbSet<Automobili> Automobili { get; set; }
        public virtual DbSet<BankovniNalozi> BankovniNalozi { get; set; }
        public virtual DbSet<BrojeviVrata> BrojeviVrata { get; set; }
        public virtual DbSet<Cijene> Cijene { get; set; }
        public virtual DbSet<Dijelovi> Dijelovi { get; set; }
        public virtual DbSet<Firme> Firme { get; set; }
        public virtual DbSet<GodineProizvodnje> GodineProizvodnje { get; set; }
        public virtual DbSet<KorisnickiNalozi> KorisnickiNalozi { get; set; }
        public virtual DbSet<Kupci> Kupci { get; set; }
        public virtual DbSet<MarkeAutomobila> MarkeAutomobila { get; set; }
        public virtual DbSet<ModeliAutomobila> ModeliAutomobila { get; set; }
        public virtual DbSet<Prodavci> Prodavci { get; set; }
        public virtual DbSet<Rabati> Rabati { get; set; }
        public virtual DbSet<Radnici> Radnici { get; set; }
        public virtual DbSet<TipoviMjenjaca> TipoviMjenjaca { get; set; }
        public virtual DbSet<VrsteGoriva> VrsteGoriva { get; set; }
    }
}
