//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Podaci
{
    using System;
    using System.Collections.Generic;
    
    public partial class StatistikeProdaje
    {
        public int Id { get; set; }
        public string Prodao { get; set; }
        public int Kupac { get; set; }
        public int Dio { get; set; }
        public int Automobil { get; set; }
        public int Cijena { get; set; }
        public Nullable<int> Rabat { get; set; }
    
        public virtual Automobili Automobili { get; set; }
        public virtual Cijene Cijene { get; set; }
        public virtual Dijelovi Dijelovi { get; set; }
        public virtual Rabati Rabati { get; set; }
    }
}
